openapi: 3.0.2
info:
  title: My API
  version: 1.0.0
  description: Description of my API
servers:
  - url: http://localhost:1323/v1
    description: local server

tags:
  - name: pets
    description: Everything about your Pets

paths:
  /pets:
    $ref: './paths/pets.yml#/paths/~1pets'
  /pets/{id}:
    $ref: './paths/pets.yml#/paths/~1pets~1{id}'
