services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/sh -c "air -c .air.toml"
    ports:
      - "1323:1323"
    volumes:
      - ./:/app
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - "13306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: prototype
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  codegen:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      /bin/bash -c \ '
        oapi-codegen \
          -config config/type.config.yml \
          spec/.dist/openapi/openapi.yaml & \
        oapi-codegen \
          -config config/router.config.yml \
          spec/.dist/openapi/openapi.yaml
      '
    depends_on:
      oapigen:
        condition: service_completed_successfully
    volumes:
      - ./:/app

  oapigen:
    image: "openapitools/openapi-generator-cli:v6.6.0"
    command: >
      /bin/bash -c \ '
        /usr/local/bin/docker-entrypoint.sh \
          generate \
            -i /app/spec/openapi.yml \
            -g openapi-yaml \
            -o /app/spec/.dist
      '
    volumes:
      - ./:/app
