// Package oas provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package oas

import (
	"time"
)

// Error defines model for Error.
type Error struct {
	Code    int32  `json:"code"`
	Message string `json:"message"`
}

// Pet defines model for Pet.
type Pet struct {
	DateOfBirth *time.Time `json:"date_of_birth,omitempty"`
	Id          uint       `json:"id"`
	Name        string     `json:"name"`
	Tag         *string    `json:"tag,omitempty"`
}

// PetRequestBody defines model for PetRequestBody.
type PetRequestBody struct {
	DateOfBirth *time.Time `json:"date_of_birth,omitempty"`
	Name        string     `json:"name"`
	Tag         *string    `json:"tag,omitempty"`
}

// Pets defines model for Pets.
type Pets struct {
	Pets []Pet `json:"pets"`
}

// CreatePetsJSONRequestBody defines body for CreatePets for application/json ContentType.
type CreatePetsJSONRequestBody = PetRequestBody

// UpdatePetJSONRequestBody defines body for UpdatePet for application/json ContentType.
type UpdatePetJSONRequestBody = PetRequestBody
